[workspace]
resolver = "3"

members = [
    "crates/worker",
    "crates/encoding",
    "crates/queue",
    "crates/storage",
    "crates/persistence",
]

[workspace.dependencies]
tokio = { version = "1.47", features = ["macros", "rt-multi-thread", "signal"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
url = "2.5"
