[package]
name = "worker"
version = "0.1.0"
edition = "2024"

[dependencies]
encoding = { path = "../encoding" }
persistence = { path = "../persistence" }
queue = { path = "../queue" }
storage = { path = "../storage" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
serde_json = "1.0"
